id = "spinel-theme"
name = "Spinel Theme"
description = "Theme for Zed, inspired by Shopify's Spinel theme for VSCode"
version = "0.1.1"
schema_version = 1
authors = ["Aidan Lavis"]
repository = "https://github.com/a-lavis/zed-spinel"
